# -*- coding: utf-8 -*-
"""scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jQySCTYb32H78PHBBSdDJZlHuIlCRAWo
"""

import requests
import bs4

request1 = requests.get('https://www.flipkart.com/lenovo-p2-grey-graphite-grey-32-gb/p/itmeq5ygebzgqgfb?pid=MOBEZFHHVD8KXE7G&lid=LSTMOBEZFHHVD8KXE7GB0OS6I&marketplace=FLIPKART&q=leonovo+p2&store=tyy%2F4io&srno=s_1_2&otracker=search&otracker1=search&fm=search-autosuggest&iid=34482a46-44ec-47bb-9c45-ab0f1baf04f8.MOBEZFHHVD8KXE7G.SEARCH&ppt=hp&ppn=homepage&ssid=61j5a7w3i5vr4pa81652813949888&qH=1eb8ff93866677e7')
request1

request1.content

soup = bs4.BeautifulSoup(request1.text)
soup

reviews = soup.findAll('div',{'class' : 't-ZTKy'});
for review in reviews:
  print(review.get_text() + "\n\n" )

ratings = soup.find('div',{'class':'_2d4LTz'}).get_text();
print(ratings)

# Individual Ratings
individual_ratings = soup.findAll('div',{'class':'_3LWZlK _1BLPMq'});
for indi_rating in individual_ratings:
  print(indi_rating.get_text() + " \n")

#tags = soup.find('span',{'class':'yhB1nd GXgmTe'}).get_text();
#tags

customer_name = soup.findAll('p',{'class':'_2sc7ZR _2V5EHH'});
for cust_name in customer_name:
  print(cust_name.get_text() + " \n")

price = soup.find('div',{'class':'_30jeq3 _16Jk6d'}).get_text();
print(price)

questions = soup.find_all('div',{'class' : '_1xR0kG _3cziW5'});
for question in questions:
  print(question.get_text())
answer = question.findNext('div',{'class':'_2yeNfb'}).get_text();
print(answer+ "\n\n")

specifications = soup.find_all('td',{'class' : '_1hKmbr'});
for specification in specifications:
  print(specification.get_text())
  answer = specification.findNext('td',{'class':'URwL2w'}).get_text();
  print(answer+ "\n\n")